# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# set number of terminal colors
export TERM="xterm-256color"

# You may need to manually set your language environment
export LANG=en_GB.UTF-8
export ZSH_CACHE_DIR=$HOME/.zsh

# load and configure zsh packet manager antigen
# depending on the current operating system
os="$(uname -s)"
case "${os}" in
  Linux*)   
    source /usr/share/zsh/share/antigen.zsh
    antigen use oh-my-zsh
    ;;
  Darwin*)  
    source /usr/local/share/antigen/antigen.zsh
    antigen use oh-my-zsh
    antigen bundle osx
    ;;
  *)
    ;;
esac

# load zsh plugins by using antigen package manager
antigen bundle git
antigen bundle npm
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen theme sunrise
antigen apply

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# 10ms for key sequences
KEYTIMEOUT=1

# include alias definitions from .aliasrc
if [[ -r ~/.aliasrc ]]; then
   . ~/.aliasrc   
fi

# start tmux session
#if [ -z $TMUX ]; then; tmux; fi
