# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# set number of terminal colors
export TERM="xterm-256color"

# Path to your oh-my-zsh installation.
export ZSH=/Users/lack/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_GB.UTF-8

# load and configure zsh packet manager antigen
source /usr/local/share/antigen/antigen.zsh
antigen bundle git
antigen bundle osx
antigen bundle npm
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen theme af-magic
antigen apply

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# include alias definitions from .aliasrc
if [[ -r ~/.aliasrc ]]; then
   . ~/.aliasrc   
fi

# start tmux session
#if [ -z $TMUX ]; then; tmux; fi
